/**
 * Generates corpus/PROVENANCE.md from the built corpus.
 *
 * Regenerated on every `pnpm corpus:build` so the provenance record cannot drift
 * from the corpus it describes. A hand-maintained table is a table that
 * eventually lies — and in this project the provenance table is the evidence.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import type { DocumentRecord } from "../build-corpus";

const BT = "`";

const paragraphCount = (d: DocumentRecord): string => {
  const uniq = new Set(
    d.chunks.map((c) => c.provenance.paragraph).filter(Boolean) as string[],
  );
  return uniq.size > 0 ? `${uniq.size} Paragraphen` : `${d.chunks.length} Abschnitte`;
};

const row = (d: DocumentRecord, i: number): string => {
  const p = d.provenance;
  const sha = p.commit_sha ? `${BT}${p.commit_sha.slice(0, 12)}${BT}` : "—";
  return (
    `| ${i + 1} | ${p.title} | ${p.abkuerzung ?? "—"} | ${paragraphCount(d)} | ` +
    `${d.chunks.length} | ${p.source_repo} | [Link](${p.source_url}) | ${sha} | ` +
    `${p.retrieved_at} | ${p.stand ?? "—"} | ${p.licence_note} | full-text | ` +
    `${p.is_synthetic ? "**JA**" : "nein"} |`
  );
};

export const writeProvenanceDoc = (
  docs: DocumentRecord[],
  commitSha: string,
): void => {
  const statutes = docs.filter((d) => !d.provenance.is_synthetic);
  const synthetic = docs.filter((d) => d.provenance.is_synthetic);
  const totalChunks = docs.reduce((n, d) => n + d.chunks.length, 0);

  const oldestStand =
    statutes
      .map((d) => d.provenance.stand)
      .filter((s): s is string => Boolean(s))
      .sort()[0] ?? "unbekannt";

  const header = [
    "| # | Titel | Abk. | Umfang | Chunks | source_repo | URL | commit_sha | retrieved_at | Stand | Lizenz | Modus | Synthetisch |",
    "|---|-------|------|--------|--------|-------------|-----|------------|--------------|-------|--------|-------|-------------|",
  ].join("\n");

  const md = `# Corpus provenance

Every document in the knowledge base: where it came from, which upstream revision
it is pinned to, and under what terms.

**Generated by ${BT}pnpm corpus:build${BT} — do not edit by hand, it will be overwritten.**

- Mirror commit: ${BT}${commitSha}${BT}
- Documents: ${docs.length} (${statutes.length} amtlich, ${synthetic.length} simuliert)
- Chunks: ${totalChunks}

## Freshness warning — read this before trusting a citation

The upstream mirror is a weekly archive that has **itself stopped updating**. Its
most recent commit is from **2025-04-02**, and the statute XML carries build dates
from **February 2025** (oldest here: ${oldestStand}).

German tax law changes continuously. Every answer drawn from this corpus reflects
the law **as of its ${BT}Stand:${BT} date, not today**. The UI prints that date on
every source for exactly this reason. Before any real use, re-ingest from the live
[gesetze-im-internet.de](https://www.gesetze-im-internet.de) XML.

Cited-but-stale is a real failure mode in tax, not a cosmetic one.

## Licence position

German statutes are **amtliche Werke** and are exempt from copyright under
**§ 5 UrhG** — they are gemeinfrei. gesetze-im-internet.de publishes the XML for
third-party use. The exemption covers the **statute text only**; it does not
extend to commercial or derived commentary, none of which is in this corpus.

The synthetic Kanzlei-Wiki was written for this demo and is not derived from any
real firm's material.

## Ingested documents

${header}
${statutes.map((d, i) => row(d, i)).join("\n")}
${synthetic.map((d, i) => row(d, statutes.length + i)).join("\n")}

**Modus** is ${BT}full-text${BT} (reuse permitted, text stored and chunked) or
${BT}link-only${BT} (reuse unclear or prohibited — citation and link only).

## Deliberate scope limits

- **Only three statutes.** EStG, UStG and AO. GewStG and KStG were present in the
  mirror and were **not** ingested — a small, correct, well-cited corpus beats a
  large noisy one, and every extra statute widens what has to be verified.
- **Section-level deep links were not fabricated.** ${BT}source_url${BT} is the
  law-level page. The per-section URL scheme could not be HTTP-verified from the
  build environment (outbound access to gesetze-im-internet.de is blocked by
  network policy), so no per-section link was invented. The law-level path *is*
  verified: the mirror's own scraper derives each folder slug from the
  gesetze-im-internet URL path (${BT}scraper.rb${BT}:
  ${BT}short_name = Pathname.new(uri.path).dirname${BT}).
- **Repeal stubs skipped.** Sections whose body is under 40 characters
  (e.g. "(weggefallen)") carry no retrievable content and were dropped.
- **Sentence numbers dropped.** The XML marks each Satz with
  ${BT}<SUP class="Rec">N</SUP>${BT}. Keeping it fuses the marker to the next word
  ("1Werbungskosten sind…"), corrupting both readability and the embedding. The
  prose itself is reproduced verbatim.

## Downgraded to link-only

| Source | Why | What we store instead |
|--------|-----|----------------------|
| _(none — all three statutes are gemeinfrei under § 5 UrhG and were ingested in full)_ | | |

## Sources evaluated and not ingested

| Source | Reason |
|--------|--------|
| GewStG, KStG | Present in the mirror, but outside the agreed tight scope. Ingest on demand. |
| BMF-Schreiben | Not attempted in this phase. Their reuse terms are **not** the § 5 UrhG statute exemption and need their own licence check before any ingest. |
`;

  writeFileSync(join(process.cwd(), "corpus", "PROVENANCE.md"), md);
};
